name: Api Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Ensure Docker is Running
        run: docker info

      - name: Run Integration Tests
        run: dotnet test ./Rankomizer.Tests.Integration/Rankomizer.Tests.Integration.csproj --configuration Release
