name: Api Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Update Appsetting.json
        env:
          API_APPSETTINGS_JSON: ${{secrets.API_APPSETTINGS_JSON}}
        shell: bash
        run: |
          echo "$API_APPSETTINGS_JSON" > Rankomizer.Server.Api/appsettings.json

      - name: Restore Dependencies
        run: dotnet restore ./Rankomizer.Tests.Integration/Rankomizer.Tests.Integration.csproj 

      - name: Ensure Docker is Running
        run: docker info

      - name: Run Integration Tests
        run: dotnet test ./Rankomizer.Tests.Integration/Rankomizer.Tests.Integration.csproj --configuration Release
